name: Automated Tests
on: pull_request
jobs: 
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-lastest
    steps:
      - uses: action/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm test
          